### ISSUE TITLE
how about multi words

### ISSUE THREAD

**Issue by munkh-altai** [pramodsum/AamMango#3]
Hello 
Thank for your online codes.

I starting new project for  "Pronunciation training and assessment " web based app.
Your code is very helpful for me.

Now am trying multi words Pronunciation check for reading training and English learning people.
my one training words average is 150 and i am trying when user say word follow highlight.
please check Example words.

Can you lead me for make this app ? you can say some way make correctly :)
your mind is very useful for me.

Example words: "What things are important in my life? Well, I've got an old car. It isn't very fast, but I love it. What else? Well, my mobile's very important to me."

sorry my English is not good

**Comment by pramodsum** [comment]
Check the repo listed in pramodsum/AamMango#4
